'use client'

import { useState } from 'react'

// ─── Types ────────────────────────────────────────────────────────────────────

interface JourneyEvent {
  date: string; type: 'enquiry' | 'booking' | 'treatment' | 'message' | 'review' | 'noshow' | 'rebooked' | 'invoice'
  title: string; detail: string
}

interface ConvMsg { role: 'lumi' | 'client'; text: string }
interface ConvSummary { id: string; channel: string; date: string; preview: string; outcome: string; messages: ConvMsg[] }
interface ClientNote { date: string; author: string; text: string }

interface FullClient {
  id: string; initials: string; name: string; status: string; avatarGradient: string
  totalSpend: string; lastVisitLabel: string; lastVisitDate: string; avgValue: string; clientSince: string
  phone: string; email: string; dob: string; address: string; referredBy: string
  firstContact: string; preferredContact: string; gdprDate: string; marketingOptIn: boolean
  allergies: string; medical: string; medication: string; contraindications: string
  patchTest: string; consentForm: string; pregnancy: string; lastUpdated: string
  preferredTreatments: string[]; declinedTreatments: string[]; treatmentNotes: string
  assessment: string; responseRate: string; avgReplyTime: string; bestContactTime: string
  journey: JourneyEvent[]; conversations: ConvSummary[]; notes: ClientNote[]
}

// ─── Data ─────────────────────────────────────────────────────────────────────

const FULL_CLIENTS: Record<string, FullClient> = {
  '1': {
    id: '1', initials: 'EW', name: 'Emma Wilson', status: 'Active', avatarGradient: 'linear-gradient(135deg,#C4973F,#E8B44B)',
    totalSpend: '£1,240', lastVisitLabel: '2 weeks ago', lastVisitDate: '18 May 2026', avgValue: '£177', clientSince: '8 months',
    phone: '+44 7700 900123', email: 'emma.wilson@email.com', dob: '14 March 1989', address: 'London, UK',
    referredBy: 'Instagram', firstContact: '12 Sep 2025', preferredContact: 'WhatsApp', gdprDate: '12 Sep 2025', marketingOptIn: true,
    allergies: 'None declared', medical: 'None', medication: 'None', contraindications: 'None',
    patchTest: '✓ Completed 12 Sep 2025', consentForm: '✓ Signed', pregnancy: 'Not pregnant', lastUpdated: '18 May 2026',
    preferredTreatments: ['Lip filler', 'Anti-wrinkle', 'Skin boosters'], declinedTreatments: ['Fat dissolving'],
    treatmentNotes: 'Prefers gradual enhancement. Very natural look. Nervous first-timer — needs extra reassurance during consultation.',
    assessment: "Emma is a high-value, loyal client with consistent rebooking behaviour. She responds best to WhatsApp messages sent Tuesday–Thursday between 6–8pm. Her average spend is increasing — she's likely open to trying skin boosters at her next visit. Recommend mentioning it naturally at consultation.",
    responseRate: '87%', avgReplyTime: '23 minutes', bestContactTime: 'Tue–Thu 6–8pm',
    journey: [
      { date: '18 May 2026', type: 'treatment', title: 'Lip filler top-up · 0.5ml', detail: 'Duration: 30 mins · £180 paid' },
      { date: '15 May 2026', type: 'message', title: 'Lumi sent appointment reminder', detail: 'Confirmed via WhatsApp' },
      { date: '10 May 2026', type: 'booking', title: 'Booked lip filler top-up', detail: 'Via Lumi — Instagram DM at 10:47pm' },
      { date: '5 May 2026', type: 'review', title: 'Left 5-star Google review', detail: 'Generated by Lumi follow-up' },
      { date: '1 May 2026', type: 'treatment', title: 'Anti-wrinkle · 2 areas', detail: 'Duration: 45 mins · £200 paid' },
      { date: '28 Apr 2026', type: 'message', title: 'Lumi sent rebooking prompt', detail: 'Emma replied within 4 minutes' },
      { date: '15 Apr 2026', type: 'rebooked', title: 'Rebooked via WhatsApp', detail: 'Lumi confirmed booking automatically' },
      { date: '12 Sep 2025', type: 'enquiry', title: 'First enquiry via Instagram', detail: 'Lip filler pricing query — converted same day' },
    ],
    conversations: [
      {
        id: 'c1', channel: 'Instagram', date: '10 May 2026', preview: 'Hi, how much is lip filler...', outcome: 'BOOKED',
        messages: [
          { role: 'client', text: 'Hi, how much is lip filler? Do you have anything this week?' },
          { role: 'lumi', text: "Hi Emma! Lip filler starts from £180 for 0.5ml. We have Thursday 2pm and Friday 11am available — both with our senior clinician. Which works for you? ✦" },
          { role: 'client', text: 'Friday 11am perfect!' },
          { role: 'lumi', text: "Booked! Friday 16 May at 11:00am confirmed. I'll send a reminder Thursday evening. See you then! ✦" },
        ],
      },
      {
        id: 'c2', channel: 'WhatsApp', date: '28 Apr 2026', preview: 'Hey lovely! Just checking...', outcome: 'REBOOKED',
        messages: [
          { role: 'lumi', text: "Hey Emma! 💛 It's been about 5 weeks since your anti-wrinkle treatment — just checking in. How are you feeling? Ready for a top-up?" },
          { role: 'client', text: "Oh yes actually, I've been meaning to book! Can you do late next week?" },
          { role: 'lumi', text: "Absolutely! We have Wednesday 6 May at 6pm or Thursday 7 May at 5:30pm. Which suits you better?" },
          { role: 'client', text: 'Thursday 5:30 please!' },
          { role: 'lumi', text: "Done! Thursday 7 May at 5:30pm confirmed. See you then Emma 🌟" },
        ],
      },
      {
        id: 'c3', channel: 'Instagram', date: '5 Apr 2026', preview: 'I had such an amazing time...', outcome: 'REVIEW LEFT',
        messages: [
          { role: 'lumi', text: "Hi Emma! How are you feeling 3 days after your lip treatment? Swelling should be settling now 💛" },
          { role: 'client', text: "I had such an amazing time, the results are stunning! Way more natural than I expected" },
          { role: 'lumi', text: "That's so lovely to hear! Your results really are gorgeous. If you have a moment, a Google review would mean the world to us — here's the link: lumio.london/review ⭐" },
          { role: 'client', text: "Just left one! 5 stars obviously 😊" },
        ],
      },
    ],
    notes: [
      { date: '18 May 2026', author: 'You', text: "Emma mentioned she's interested in trying skin boosters next time. Very happy with her lip results — said they look the most natural she's ever had." },
      { date: '12 Sep 2025', author: 'You', text: "First time client. Very nervous at consultation. Needed extra time to feel comfortable. Worth spending more time with her at future visits." },
      { date: '5 Apr 2026', author: 'Lumi', text: "Emma has opened every WhatsApp message within 30 minutes on weekday evenings." },
    ],
  },
  '2': {
    id: '2', initials: 'SC', name: 'Sophie Carter', status: 'Due rebooking', avatarGradient: 'linear-gradient(135deg,#5B8A68,#7DB88A)',
    totalSpend: '£2,180', lastVisitLabel: '7 weeks ago', lastVisitDate: '1 Apr 2026', avgValue: '£182', clientSince: '14 months',
    phone: '+44 7700 900456', email: 'sophie.carter@email.com', dob: '8 July 1992', address: 'London, UK',
    referredBy: 'Friend referral', firstContact: '3 Mar 2025', preferredContact: 'WhatsApp', gdprDate: '3 Mar 2025', marketingOptIn: true,
    allergies: 'None declared', medical: 'None', medication: 'None', contraindications: 'None',
    patchTest: '✓ Completed 3 Mar 2025', consentForm: '✓ Signed', pregnancy: 'Not pregnant', lastUpdated: '1 Apr 2026',
    preferredTreatments: ['Botox', 'Lip filler', 'Russian lips'], declinedTreatments: [],
    treatmentNotes: 'Prefers dramatic results. High volume lip filler. Bold look preferred.',
    assessment: "Sophie is our highest-value returning client. She typically books every 6 weeks and is now 7 weeks since her last visit — she is overdue and at risk of booking elsewhere. A personalised WhatsApp message this evening would likely convert.",
    responseRate: '94%', avgReplyTime: '12 minutes', bestContactTime: 'Mon–Wed 7–9pm',
    journey: [
      { date: '1 Apr 2026', type: 'treatment', title: 'Russian lips · 1.5ml', detail: 'Duration: 45 mins · £280 paid' },
      { date: '29 Mar 2026', type: 'booking', title: 'Booked Russian lips', detail: 'Via Lumi — WhatsApp' },
      { date: '15 Feb 2026', type: 'treatment', title: 'Botox · 3 areas', detail: 'Duration: 45 mins · £280 paid' },
      { date: '3 Jan 2026', type: 'treatment', title: 'Lip filler · 1ml', detail: 'Duration: 30 mins · £220 paid' },
      { date: '20 Nov 2025', type: 'review', title: 'Left 5-star Google review', detail: 'Unprompted — shared on Instagram' },
      { date: '3 Mar 2025', type: 'enquiry', title: 'First enquiry', detail: 'Referral from existing client' },
    ],
    conversations: [
      {
        id: 'c1', channel: 'WhatsApp', date: '1 Apr 2026', preview: "Wednesday please", outcome: 'BOOKED',
        messages: [
          { role: 'lumi', text: "Hi Sophie! It's been around 6 weeks since your last visit — just checking in. How's your treatment looking? We have some lovely availability this week." },
          { role: 'client', text: "Oh wow yes actually, it's started to fade a bit!" },
          { role: 'lumi', text: "Great timing! We have Wednesday 29 May at 3:30pm or Friday 31 May at 11:00am. Which works better?" },
          { role: 'client', text: "Wednesday please" },
          { role: 'lumi', text: "Booked! Wednesday 29 May at 3:30pm. I'll send a reminder 48 hours before. See you then Sophie." },
        ],
      },
    ],
    notes: [
      { date: '1 Apr 2026', author: 'You', text: "Sophie mentioned she's thinking about cheek filler at her next visit. Keep in mind for the consultation." },
    ],
  },
  '3': {
    id: '3', initials: 'CR', name: 'Charlotte Reed', status: 'New', avatarGradient: 'linear-gradient(135deg,#8B7BAB,#A99BC4)',
    totalSpend: '£450', lastVisitLabel: '1 week ago', lastVisitDate: '10 May 2026', avgValue: '£150', clientSince: '1 month',
    phone: '+44 7700 900789', email: 'charlotte.reed@email.com', dob: '22 November 1995', address: 'London, UK',
    referredBy: 'Google search', firstContact: '8 Apr 2026', preferredContact: 'Email', gdprDate: '8 Apr 2026', marketingOptIn: false,
    allergies: 'None declared', medical: 'None', medication: 'None', contraindications: 'None',
    patchTest: '✓ Completed 8 Apr 2026', consentForm: '✓ Signed', pregnancy: 'Not pregnant', lastUpdated: '10 May 2026',
    preferredTreatments: ['Botox'], declinedTreatments: ['Lip filler'],
    treatmentNotes: 'First-time aesthetics client. Very cautious — prefers to start small. Frown lines only for now.',
    assessment: "Charlotte is a new client who found us via Google. She's had one treatment and is a good candidate for rebooking. Her next appointment is already in the diary for 28 May — ensure Lumi sends a pre-appointment message to build confidence.",
    responseRate: '72%', avgReplyTime: '4 hours', bestContactTime: 'Weekday evenings',
    journey: [
      { date: '10 May 2026', type: 'treatment', title: 'Botox · frown lines', detail: 'Duration: 30 mins · £180 paid' },
      { date: '8 May 2026', type: 'booking', title: 'Confirmed appointment', detail: 'Via email' },
      { date: '8 Apr 2026', type: 'enquiry', title: 'First website enquiry', detail: 'Botox pricing query' },
    ],
    conversations: [
      {
        id: 'c1', channel: 'Website', date: '8 Apr 2026', preview: 'Evening if possible', outcome: 'BOOKED',
        messages: [
          { role: 'client', text: "Hi, I'm interested in Botox — never had it before. How much does it cost?" },
          { role: 'lumi', text: "Hi Charlotte! Great to hear from you. Our Botox starts from £180 for one area. First consultations are always free. Which area were you thinking about?" },
          { role: 'client', text: "Mainly frown lines" },
          { role: 'lumi', text: "Lovely choice — very natural results. We have slots this week. Would you prefer daytime or evening?" },
          { role: 'client', text: "Evening if possible" },
          { role: 'lumi', text: "We have Tuesday 28 May at 6:00pm — shall I reserve that for you?" },
        ],
      },
    ],
    notes: [],
  },
  '4': {
    id: '4', initials: 'OB', name: 'Olivia Bennett', status: 'Active', avatarGradient: 'linear-gradient(135deg,#C4973F,#E8B44B)',
    totalSpend: '£890', lastVisitLabel: '3 weeks ago', lastVisitDate: '20 May 2026', avgValue: '£178', clientSince: '10 months',
    phone: '+44 7700 900012', email: 'olivia.bennett@email.com', dob: '3 June 1990', address: 'London, UK',
    referredBy: 'Instagram', firstContact: '15 Jul 2025', preferredContact: 'Instagram DM', gdprDate: '15 Jul 2025', marketingOptIn: true,
    allergies: 'None declared', medical: 'None', medication: 'None', contraindications: 'None',
    patchTest: '✓ Completed 15 Jul 2025', consentForm: '✓ Signed', pregnancy: 'Not pregnant', lastUpdated: '20 May 2026',
    preferredTreatments: ['Lip filler', 'Cheek filler'], declinedTreatments: [],
    treatmentNotes: 'Very pleased with results. Tends to book cheek filler annually and lip filler every 4–6 months.',
    assessment: "Olivia is an engaged, loyal client with a clear treatment pattern. She responds well to Instagram DMs and typically books within 24 hours of being contacted. She's due for a lip top-up in the next 4–6 weeks.",
    responseRate: '91%', avgReplyTime: '45 minutes', bestContactTime: 'Sat–Sun afternoons',
    journey: [
      { date: '20 May 2026', type: 'treatment', title: 'Lip filler · 0.5ml top-up', detail: 'Duration: 20 mins · £150 paid' },
      { date: '15 Jan 2026', type: 'treatment', title: 'Cheek filler · 1ml', detail: 'Duration: 40 mins · £280 paid' },
      { date: '15 Jul 2025', type: 'enquiry', title: 'First Instagram enquiry', detail: 'Lip filler' },
    ],
    conversations: [],
    notes: [{ date: '20 May 2026', author: 'You', text: "Olivia asked about cheek filler top-up for next year. Note to follow up in January." }],
  },
  '5': {
    id: '5', initials: 'GM', name: 'Grace Mitchell', status: 'Due rebooking', avatarGradient: 'linear-gradient(135deg,#6B8FAB,#89AAC4)',
    totalSpend: '£1,560', lastVisitLabel: '6 weeks ago', lastVisitDate: '5 Apr 2026', avgValue: '£195', clientSince: '12 months',
    phone: '+44 7700 900345', email: 'grace.mitchell@email.com', dob: '17 February 1988', address: 'London, UK',
    referredBy: 'Friend referral', firstContact: '8 May 2025', preferredContact: 'WhatsApp', gdprDate: '8 May 2025', marketingOptIn: true,
    allergies: 'None declared', medical: 'None', medication: 'None', contraindications: 'None',
    patchTest: '✓ Completed 8 May 2025', consentForm: '✓ Signed', pregnancy: 'Not pregnant', lastUpdated: '5 Apr 2026',
    preferredTreatments: ['Botox', 'Filler'], declinedTreatments: [],
    treatmentNotes: 'Regular client with a predictable 6-week booking cycle. Very easy to deal with.',
    assessment: "Grace books like clockwork every 6 weeks and is currently 1 week overdue. A simple check-in message should convert quickly. She's referred 2 other clients to the clinic.",
    responseRate: '88%', avgReplyTime: '1 hour', bestContactTime: 'Weekday lunchtimes',
    journey: [
      { date: '5 Apr 2026', type: 'treatment', title: 'Botox + filler combo', detail: 'Duration: 60 mins · £380 paid' },
      { date: '10 Feb 2026', type: 'treatment', title: 'Botox · 3 areas', detail: 'Duration: 45 mins · £280 paid' },
      { date: '8 May 2025', type: 'enquiry', title: 'First enquiry', detail: 'WhatsApp — referral' },
    ],
    conversations: [],
    notes: [],
  },
  '6': {
    id: '6', initials: 'AC', name: 'Amelia Clarke', status: 'New', avatarGradient: 'linear-gradient(135deg,#AB7B6B,#C49989)',
    totalSpend: '£280', lastVisitLabel: '1 week ago', lastVisitDate: '12 May 2026', avgValue: '£280', clientSince: '3 weeks',
    phone: '+44 7700 900678', email: 'amelia.clarke@email.com', dob: '29 August 1998', address: 'London, UK',
    referredBy: 'Google', firstContact: '24 Apr 2026', preferredContact: 'WhatsApp', gdprDate: '24 Apr 2026', marketingOptIn: false,
    allergies: 'None declared', medical: 'None', medication: 'None', contraindications: 'None',
    patchTest: '✓ Completed 24 Apr 2026', consentForm: '✓ Signed', pregnancy: 'Not pregnant', lastUpdated: '12 May 2026',
    preferredTreatments: ['Dermaplaning'], declinedTreatments: [],
    treatmentNotes: 'Young client — interested in skin health and maintenance treatments rather than injectables.',
    assessment: "Amelia is a new client focused on skin treatments. She may be a long-term client if nurtured correctly. Consider recommending a skin booster course at her next visit.",
    responseRate: '65%', avgReplyTime: '3 hours', bestContactTime: 'Weekday evenings',
    journey: [
      { date: '12 May 2026', type: 'treatment', title: 'Dermaplaning session', detail: 'Duration: 45 mins · £280 paid' },
      { date: '24 Apr 2026', type: 'enquiry', title: 'Google enquiry', detail: 'Skin treatments query' },
    ],
    conversations: [],
    notes: [],
  },
  '7': {
    id: '7', initials: 'IM', name: 'Isabelle Moore', status: 'VIP', avatarGradient: 'linear-gradient(135deg,#7BAB8B,#9AC4A9)',
    totalSpend: '£3,200', lastVisitLabel: '3 weeks ago', lastVisitDate: '22 May 2026', avgValue: '£213', clientSince: '18 months',
    phone: '+44 7700 900901', email: 'isabelle.moore@email.com', dob: '12 April 1986', address: 'London, UK',
    referredBy: 'Referral from Sophie Carter', firstContact: '15 Nov 2024', preferredContact: 'Phone', gdprDate: '15 Nov 2024', marketingOptIn: true,
    allergies: 'None declared', medical: 'None', medication: 'Vitamin D supplement', contraindications: 'None',
    patchTest: '✓ Completed 15 Nov 2024', consentForm: '✓ Signed', pregnancy: 'Not pregnant', lastUpdated: '22 May 2026',
    preferredTreatments: ['Lip filler', 'Botox', 'Hydrafacial', 'Cheek filler'], declinedTreatments: ['Thread lift'],
    treatmentNotes: 'VIP client — prefers to be called to book rather than messaged. Book her into premium appointment slots.',
    assessment: "Isabelle is our highest-spending client and a significant brand ambassador — she has referred 4 clients. She requires a premium, personal experience. Always ensure her appointments have a buffer before and after. She appreciates being remembered.",
    responseRate: '78%', avgReplyTime: '2 hours', bestContactTime: 'Tue/Thu mornings',
    journey: [
      { date: '22 May 2026', type: 'treatment', title: 'Botox + Hydrafacial combo', detail: 'Duration: 90 mins · £420 paid' },
      { date: '1 Apr 2026', type: 'treatment', title: 'Lip filler + cheek filler', detail: 'Duration: 60 mins · £500 paid' },
      { date: '10 Jan 2026', type: 'treatment', title: 'Anti-wrinkle · 3 areas', detail: 'Duration: 45 mins · £280 paid' },
      { date: '15 Nov 2024', type: 'enquiry', title: 'First enquiry — phone call', detail: 'Referral from Sophie Carter' },
    ],
    conversations: [],
    notes: [
      { date: '22 May 2026', author: 'You', text: "Isabelle mentioned she has a wedding to attend in July — she'll want to book before then. Remind Lumi to follow up in June." },
    ],
  },
  '8': {
    id: '8', initials: 'HT', name: 'Hannah Taylor', status: 'Lapsed', avatarGradient: 'linear-gradient(135deg,#AB8B7B,#C4A999)',
    totalSpend: '£670', lastVisitLabel: '14 weeks ago', lastVisitDate: '12 Feb 2026', avgValue: '£168', clientSince: '9 months',
    phone: '+44 7700 900234', email: 'hannah.taylor@email.com', dob: '5 October 1994', address: 'London, UK',
    referredBy: 'Instagram', firstContact: '20 Aug 2025', preferredContact: 'Instagram DM', gdprDate: '20 Aug 2025', marketingOptIn: true,
    allergies: 'None declared', medical: 'None', medication: 'None', contraindications: 'None',
    patchTest: '✓ Completed 20 Aug 2025', consentForm: '✓ Signed', pregnancy: 'Unknown', lastUpdated: '12 Feb 2026',
    preferredTreatments: ['Lip filler', 'Skin booster'], declinedTreatments: [],
    treatmentNotes: 'Lapsed client — had 4 treatments then stopped booking. Unknown reason. May have moved to a competitor.',
    assessment: "Hannah has been inactive for 14 weeks which is unusual given her previous 6-week booking cycle. Lumi has sent 2 re-engagement messages with no response. Consider a more personal outreach or a special offer to win her back.",
    responseRate: '30%', avgReplyTime: 'No recent response', bestContactTime: 'Previously: weekend evenings',
    journey: [
      { date: '12 Feb 2026', type: 'treatment', title: 'Lip filler · 1ml', detail: 'Duration: 30 mins · £220 paid' },
      { date: '18 Feb 2026', type: 'message', title: 'Lumi sent win-back message', detail: 'No response' },
      { date: '3 Mar 2026', type: 'message', title: 'Second re-engagement attempt', detail: 'No response — marked as lapsed' },
      { date: '20 Aug 2025', type: 'enquiry', title: 'First Instagram enquiry', detail: 'Lip filler pricing' },
    ],
    conversations: [],
    notes: [
      { date: '3 Mar 2026', author: 'Lumi', text: "Hannah has not responded to 2 re-engagement messages. Status updated to Lapsed." },
    ],
  },
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

const STATUS_STYLE: Record<string, { bg: string; color: string; border?: string }> = {
  Active:          { bg: 'rgba(91,138,104,0.12)', color: '#5B8A68' },
  'Due rebooking': { bg: 'rgba(196,151,63,0.12)', color: '#C4973F' },
  New:             { bg: 'rgba(91,104,138,0.12)', color: '#5B6A8A' },
  VIP:             { bg: 'rgba(196,151,63,0.2)', color: '#C4973F', border: '1px solid rgba(196,151,63,0.4)' },
  Lapsed:          { bg: 'rgba(138,91,91,0.12)', color: '#8A5B5B' },
}

function StatusBadge({ status }: { status: string }) {
  const s = STATUS_STYLE[status] ?? { bg: 'rgba(0,0,0,0.08)', color: '#8A8278' }
  return (
    <span style={{
      fontFamily: 'var(--font-inter), Inter, sans-serif', fontWeight: 600, fontSize: 10,
      textTransform: 'uppercase', letterSpacing: '0.12em',
      background: s.bg, color: s.color, border: s.border,
      borderRadius: 99, padding: '3px 10px',
    }}>
      {status}
    </span>
  )
}

function Toggle({ on, onChange }: { on: boolean; onChange: () => void }) {
  return (
    <button type="button" onClick={onChange} style={{
      width: 44, height: 24, borderRadius: 99, flexShrink: 0,
      background: on ? '#C4973F' : 'rgba(138,130,120,0.3)',
      position: 'relative', cursor: 'pointer', border: 'none',
      transition: 'background 200ms',
    }}>
      <div style={{
        width: 18, height: 18, borderRadius: '50%', background: '#FFFDF8',
        position: 'absolute', top: 3, left: on ? 23 : 3,
        transition: 'left 200ms', boxShadow: '0 1px 3px rgba(0,0,0,0.2)',
      }} />
    </button>
  )
}

const DOT_COLOR: Record<string, string> = {
  enquiry: '#C4973F', booking: '#C4973F', treatment: '#5B8A68',
  message: '#8A8278', review: '#5B8A68', noshow: '#E8B44B',
  rebooked: '#5B8A68', invoice: '#8A8278',
}

// ─── Tab components ───────────────────────────────────────────────────────────

function OverviewTab({ client, dm }: { client: FullClient; dm: boolean }) {
  const cardBg = dm ? 'rgba(255,253,248,0.04)' : 'rgba(255,255,255,0.72)'
  const border = dm ? 'rgba(255,253,248,0.08)' : 'rgba(26,24,20,0.08)'
  const textPri = dm ? '#FFFDF8' : '#1A1814'
  const textSec = dm ? 'rgba(255,253,248,0.5)' : '#8A8278'
  const textMut = dm ? 'rgba(255,253,248,0.35)' : 'rgba(26,24,20,0.4)'

  const card = (children: React.ReactNode, goldBorder?: boolean) => (
    <div style={{
      background: cardBg, border: `1px solid ${border}`, borderRadius: '1rem', padding: '1.25rem', marginBottom: '1rem',
      borderLeft: goldBorder ? '3px solid #C4973F' : undefined,
    }}>
      {children}
    </div>
  )

  const sectionLabel = (label: string) => (
    <p style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 10, fontWeight: 600, letterSpacing: '0.14em', textTransform: 'uppercase' as const, color: '#C4973F', margin: '0 0 0.75rem' }}>{label}</p>
  )

  const row = (label: string, value: string) => (
    <div key={label} style={{ display: 'flex', justifyContent: 'space-between', padding: '5px 0', borderBottom: `1px solid ${dm ? 'rgba(255,253,248,0.04)' : 'rgba(26,24,20,0.04)'}` }}>
      <span style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 12, fontWeight: 500, color: textSec }}>{label}</span>
      <span style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 12, color: textPri, textAlign: 'right' as const, maxWidth: '60%' }}>{value}</span>
    </div>
  )

  return (
    <div>
      {card(
        <>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.75rem' }}>
            {sectionLabel('Personal Details')}
            <button style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 12, fontWeight: 500, color: textSec, background: 'none', border: 'none', cursor: 'pointer' }}>Edit</button>
          </div>
          {row('Full name', client.name)}
          {row('Phone', client.phone)}
          {row('Email', client.email)}
          {row('Date of birth', client.dob)}
          {row('Address', client.address)}
          {row('Referred by', client.referredBy)}
          {row('First contact', client.firstContact)}
          {row('Preferred contact', client.preferredContact)}
          {row('GDPR consent', `✓ Given ${client.gdprDate}`)}
          {row('Marketing opt-in', client.marketingOptIn ? '✓ Yes' : '✗ No')}
        </>
      )}

      {card(
        <>
          {sectionLabel('Medical & Treatment Notes')}
          {client.allergies !== 'None declared' && (
            <div style={{ background: 'rgba(196,151,63,0.08)', border: '1px solid rgba(196,151,63,0.3)', borderRadius: '0.5rem', padding: '0.75rem 1rem', marginBottom: '0.75rem' }}>
              <span style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 13, color: '#C4973F' }}>⚠ Review allergy notes before treatment</span>
            </div>
          )}
          {row('Allergies', client.allergies)}
          {row('Medical conditions', client.medical)}
          {row('Current medication', client.medication)}
          {row('Contraindications', client.contraindications)}
          {row('Patch test', client.patchTest)}
          {row('Consultation form', client.consentForm)}
          {row('Pregnancy status', client.pregnancy)}
          {row('Last updated', client.lastUpdated)}
        </>
      )}

      {card(
        <>
          {sectionLabel('Treatment Preferences')}
          <div style={{ marginBottom: '0.5rem' }}>
            <p style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 11, color: textMut, margin: '0 0 6px' }}>Preferred</p>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
              {client.preferredTreatments.map(t => (
                <span key={t} style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 11, fontWeight: 500, background: 'rgba(196,151,63,0.12)', color: '#C4973F', borderRadius: 99, padding: '4px 10px' }}>{t}</span>
              ))}
            </div>
          </div>
          {client.declinedTreatments.length > 0 && (
            <div style={{ marginBottom: '0.5rem' }}>
              <p style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 11, color: textMut, margin: '0 0 6px' }}>Declined</p>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
                {client.declinedTreatments.map(t => (
                  <span key={t} style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 11, fontWeight: 500, background: dm ? 'rgba(255,253,248,0.06)' : '#F9EDE8', color: textSec, borderRadius: 99, padding: '4px 10px' }}>{t} ×</span>
                ))}
              </div>
            </div>
          )}
          <p style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 13, fontStyle: 'italic', color: textSec, lineHeight: 1.6, margin: '0.75rem 0 0' }}>{client.treatmentNotes}</p>
        </>
      )}

      {card(
        <>
          {sectionLabel("Lumi's Assessment")}
          <p style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 14, color: textSec, lineHeight: 1.7, margin: '0 0 1rem' }}>{client.assessment}</p>
          <div style={{ display: 'flex', gap: '1rem', flexWrap: 'wrap' as const }}>
            {[
              { label: 'Response rate', value: client.responseRate },
              { label: 'Avg reply time', value: client.avgReplyTime },
              { label: 'Best contact', value: client.bestContactTime },
            ].map(s => (
              <div key={s.label} style={{ flex: 1, minWidth: 100 }}>
                <p style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 11, color: textMut, margin: '0 0 2px' }}>{s.label}</p>
                <p style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 13, fontWeight: 600, color: textPri, margin: 0 }}>{s.value}</p>
              </div>
            ))}
          </div>
        </>,
        true
      )}
    </div>
  )
}

function JourneyTab({ client, dm }: { client: FullClient; dm: boolean }) {
  const [expanded, setExpanded] = useState(false)
  const textPri = dm ? '#FFFDF8' : '#1A1814'
  const textSec = dm ? 'rgba(255,253,248,0.5)' : '#8A8278'
  const borderClr = dm ? 'rgba(255,253,248,0.08)' : 'rgba(26,24,20,0.08)'
  const events = expanded ? client.journey : client.journey.slice(0, 5)

  return (
    <div style={{ position: 'relative', paddingLeft: '1.5rem' }}>
      <div style={{ position: 'absolute', left: 6, top: 0, bottom: 0, width: 1, background: borderClr }} />
      {events.map((ev, i) => (
        <div key={i} style={{ position: 'relative', paddingBottom: '1.5rem' }}>
          <div style={{ position: 'absolute', left: -21, top: 4, width: 10, height: 10, borderRadius: '50%', background: DOT_COLOR[ev.type] ?? '#8A8278', border: `2px solid ${dm ? '#141210' : '#FFFDF8'}` }} />
          <p style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 11, color: textSec, margin: '0 0 3px' }}>{ev.date}</p>
          <p style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 14, fontWeight: 600, color: textPri, margin: '0 0 2px' }}>{ev.title}</p>
          <p style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 12, color: textSec, margin: 0 }}>{ev.detail}</p>
        </div>
      ))}
      {client.journey.length > 5 && (
        <button onClick={() => setExpanded(e => !e)} style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontWeight: 500, fontSize: 13, color: '#C4973F', background: 'none', border: 'none', cursor: 'pointer', padding: 0 }}>
          {expanded ? 'Show less' : `Load more (${client.journey.length - 5} more)`}
        </button>
      )}
    </div>
  )
}

function ConversationsTab({ client, dm }: { client: FullClient; dm: boolean }) {
  const [selId, setSelId] = useState(client.conversations[0]?.id ?? '')
  const cardBg = dm ? 'rgba(255,253,248,0.04)' : 'rgba(255,255,255,0.72)'
  const border = dm ? 'rgba(255,253,248,0.08)' : 'rgba(26,24,20,0.08)'
  const textPri = dm ? '#FFFDF8' : '#1A1814'
  const textSec = dm ? 'rgba(255,253,248,0.5)' : '#8A8278'
  const selected = client.conversations.find(c => c.id === selId)

  const OUTCOME_COLOR: Record<string, string> = { BOOKED: '#5B8A68', REBOOKED: '#C4973F', 'REVIEW LEFT': '#5B6A8A' }

  if (client.conversations.length === 0) {
    return <p style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 14, color: textSec, padding: '2rem 0', textAlign: 'center' as const }}>No conversations recorded for this client yet.</p>
  }

  return (
    <div style={{ display: 'flex', gap: '1rem', height: 400 }}>
      <div style={{ width: '35%', overflow: 'auto', borderRight: `1px solid ${border}` }}>
        {client.conversations.map(c => (
          <button key={c.id} type="button" onClick={() => setSelId(c.id)} style={{
            width: '100%', display: 'flex', flexDirection: 'column', gap: 4, padding: '0.75rem',
            background: selId === c.id ? (dm ? 'rgba(196,151,63,0.08)' : '#FFF4DD') : 'transparent',
            border: 'none', cursor: 'pointer', textAlign: 'left' as const,
            borderBottom: `1px solid ${border}`,
          }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', gap: 4 }}>
              <span style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 11, fontWeight: 600, color: '#C4973F' }}>{c.channel}</span>
              <span style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 10, fontWeight: 600, background: `${OUTCOME_COLOR[c.outcome]}22`, color: OUTCOME_COLOR[c.outcome] ?? textSec, borderRadius: 99, padding: '2px 6px' }}>{c.outcome}</span>
            </div>
            <span style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 11, color: textSec }}>{c.date}</span>
            <span style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 12, color: textPri, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' as const }}>{c.preview}</span>
          </button>
        ))}
      </div>
      <div style={{ flex: 1, overflow: 'auto', display: 'flex', flexDirection: 'column', gap: 12, padding: '0.25rem 0' }}>
        {selected?.messages.map((msg, i) => (
          <div key={i} style={{ display: 'flex', flexDirection: msg.role === 'client' ? 'row-reverse' : 'row', gap: 8, alignItems: 'flex-end' }}>
            {msg.role === 'lumi' && (
              <div style={{ width: 28, height: 28, borderRadius: 10, background: '#1A1814', flexShrink: 0, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                <div style={{ width: 8, height: 8, borderRadius: '50%', background: '#E8B44B', boxShadow: '0 0 8px rgba(232,180,75,.9)' }} />
              </div>
            )}
            <div style={{
              maxWidth: '78%', borderRadius: msg.role === 'lumi' ? '16px 16px 16px 4px' : '16px 16px 4px 16px',
              padding: '10px 14px', fontSize: 13, lineHeight: 1.6,
              background: msg.role === 'lumi' ? (dm ? 'rgba(255,253,248,0.08)' : '#1A1814') : (dm ? 'rgba(196,151,63,0.15)' : '#F9EDE8'),
              color: msg.role === 'lumi' ? (dm ? '#FFFDF8' : '#FFFDF8') : textPri,
              fontFamily: 'var(--font-inter), Inter, sans-serif',
            }}>
              {msg.text}
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

function NotesTab({ client, dm }: { client: FullClient; dm: boolean }) {
  const [notes, setNotes] = useState<typeof client.notes>(client.notes)
  const [newNote, setNewNote] = useState('')
  const cardBg = dm ? 'rgba(255,253,248,0.04)' : 'rgba(255,255,255,0.72)'
  const border = dm ? 'rgba(255,253,248,0.08)' : 'rgba(26,24,20,0.08)'
  const textPri = dm ? '#FFFDF8' : '#1A1814'
  const textSec = dm ? 'rgba(255,253,248,0.5)' : '#8A8278'
  const inputBg = dm ? 'rgba(255,253,248,0.06)' : '#FFFFFF'

  const save = () => {
    if (!newNote.trim()) return
    setNotes(prev => [{ date: 'Just now', author: 'You', text: newNote.trim() }, ...prev])
    setNewNote('')
  }

  return (
    <div>
      {notes.map((note, i) => (
        <div key={i} style={{ background: cardBg, border: `1px solid ${border}`, borderRadius: '0.75rem', padding: '1rem', marginBottom: '0.75rem' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 6 }}>
            <span style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 11, fontWeight: 600, color: note.author === 'Lumi' ? '#C4973F' : textSec }}>
              {note.author} · {note.date}
            </span>
          </div>
          <p style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 13, color: textPri, lineHeight: 1.6, margin: 0 }}>{note.text}</p>
        </div>
      ))}
      <div style={{ marginTop: '1rem' }}>
        <textarea
          value={newNote} onChange={e => setNewNote(e.target.value)}
          placeholder={`Add a note about ${client.name.split(' ')[0]}...`}
          rows={3}
          style={{
            width: '100%', fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 14,
            background: inputBg, color: textPri, border: `1px solid ${border}`, borderRadius: '0.75rem',
            padding: '12px', resize: 'none', outline: 'none', boxSizing: 'border-box' as const,
          }}
        />
        <button onClick={save} style={{
          marginTop: 8, width: '100%', fontFamily: 'var(--font-inter), Inter, sans-serif', fontWeight: 600, fontSize: 13,
          background: '#C4973F', color: '#1A1814', border: 'none', borderRadius: '0.75rem', padding: '12px', cursor: 'pointer',
        }}>
          Save note →
        </button>
      </div>
    </div>
  )
}

function SettingsTab({ client, dm }: { client: FullClient; dm: boolean }) {
  const [ts, setTs] = useState({
    canMessage: true, rebooking: true, reviews: true,
    marketing: client.marketingOptIn, birthday: true, reminders: true,
  })
  const textPri = dm ? '#FFFDF8' : '#1A1814'
  const textSec = dm ? 'rgba(255,253,248,0.5)' : '#8A8278'
  const border = dm ? 'rgba(255,253,248,0.08)' : 'rgba(26,24,20,0.08)'

  const rows = [
    { key: 'canMessage', label: 'Lumi can message this client' },
    { key: 'rebooking', label: 'Include in rebooking sequences' },
    { key: 'reviews', label: 'Send review requests' },
    { key: 'marketing', label: 'Marketing messages' },
    { key: 'birthday', label: 'Birthday message' },
    { key: 'reminders', label: 'Send appointment reminders' },
  ] as { key: keyof typeof ts; label: string }[]

  return (
    <div>
      <div style={{ marginBottom: '1.5rem' }}>
        {rows.map(({ key, label }) => (
          <div key={key} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '0.875rem 0', borderBottom: `1px solid ${border}` }}>
            <span style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 14, color: textPri }}>{label}</span>
            <Toggle on={ts[key]} onChange={() => setTs(prev => ({ ...prev, [key]: !prev[key] }))} />
          </div>
        ))}
      </div>

      <div style={{ borderTop: `1px solid rgba(180,60,60,0.2)`, paddingTop: '1rem' }}>
        <p style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 10, fontWeight: 600, letterSpacing: '0.14em', textTransform: 'uppercase' as const, color: textSec, margin: '0 0 0.75rem' }}>Client Data</p>
        <div style={{ display: 'flex', gap: 8, marginBottom: '0.75rem' }}>
          <button style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 13, fontWeight: 500, color: textSec, background: 'none', border: `1px solid ${border}`, borderRadius: '0.5rem', padding: '8px 16px', cursor: 'pointer' }}>Export client data</button>
          <button style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 13, fontWeight: 500, color: '#B35A4C', background: 'none', border: '1px solid rgba(179,90,76,0.3)', borderRadius: '0.5rem', padding: '8px 16px', cursor: 'pointer' }}>Archive client</button>
        </div>
        <p style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 12, color: textSec, lineHeight: 1.6, margin: 0 }}>
          Archiving removes this client from active lists but preserves all data for compliance. GDPR compliant.
        </p>
      </div>
    </div>
  )
}

// ─── Main export ──────────────────────────────────────────────────────────────

type ProfileTab = 'overview' | 'journey' | 'conversations' | 'notes' | 'settings'

export default function ClientProfile({ clientId, darkMode: dm }: { clientId: string; darkMode: boolean }) {
  const [profileTab, setProfileTab] = useState<ProfileTab>('overview')
  const [toast, setToast] = useState('')
  const client = FULL_CLIENTS[clientId]

  if (!client) return null

  const textPri = dm ? '#FFFDF8' : '#1A1814'
  const textSec = dm ? 'rgba(255,253,248,0.5)' : '#8A8278'
  const border = dm ? 'rgba(255,253,248,0.08)' : 'rgba(26,24,20,0.08)'

  const fireToast = (msg: string) => { setToast(msg); setTimeout(() => setToast(''), 3000) }

  const TABS: { id: ProfileTab; label: string }[] = [
    { id: 'overview', label: 'Overview' },
    { id: 'journey', label: 'Journey' },
    { id: 'conversations', label: 'Conversations' },
    { id: 'notes', label: 'Notes' },
    { id: 'settings', label: 'Settings' },
  ]

  return (
    <div style={{ height: '100%', overflowY: 'auto' }}>

      {/* Profile header */}
      <div style={{ padding: '0 0 1rem', borderBottom: `1px solid ${border}`, marginBottom: '1rem' }}>
        <div style={{ display: 'flex', alignItems: 'flex-start', gap: '1rem', marginBottom: '1rem' }}>
          <div style={{
            width: 56, height: 56, borderRadius: '50%', background: client.avatarGradient,
            display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
            fontFamily: 'var(--font-inter), Inter, sans-serif', fontWeight: 700, fontSize: 20, color: '#1A1814',
          }}>
            {client.initials}
          </div>
          <div style={{ flex: 1 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 4 }}>
              <span style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontWeight: 700, fontSize: 20, color: textPri }}>{client.name}</span>
              <StatusBadge status={client.status} />
            </div>
            <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' as const }}>
              {[
                { label: 'Message →', action: () => fireToast(`Lumi sent a message to ${client.name.split(' ')[0]}`) },
                { label: 'Book appointment →', action: () => fireToast('Appointment booking opened') },
                { label: 'View conversation →', action: () => setProfileTab('conversations') },
              ].map(({ label, action }) => (
                <button key={label} onClick={action} style={{
                  fontFamily: 'var(--font-inter), Inter, sans-serif', fontWeight: 500, fontSize: 12,
                  background: 'transparent', border: '1px solid rgba(196,151,63,0.3)',
                  borderRadius: 99, padding: '5px 12px', color: '#C4973F', cursor: 'pointer', transition: 'all 200ms',
                }}>
                  {label}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Quick stats row */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: '0.75rem' }}>
          {[
            { label: 'Total spend', value: client.totalSpend, sub: `across ${client.totalSpend === '£1,240' ? '7' : '5'} visits` },
            { label: 'Last visit', value: client.lastVisitLabel, sub: client.lastVisitDate },
            { label: 'Avg treatment', value: client.avgValue, sub: 'per session' },
            { label: 'Client since', value: client.clientSince, sub: 'months ago' },
          ].map(stat => (
            <div key={stat.label} style={{ textAlign: 'center' as const }}>
              <p style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 11, color: textSec, margin: '0 0 2px' }}>{stat.label}</p>
              <p style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontWeight: 700, fontSize: stat.label === 'Total spend' ? 16 : 14, color: stat.label === 'Total spend' ? '#C4973F' : textPri, margin: 0 }}>{stat.value}</p>
              <p style={{ fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 10, color: textSec, margin: '1px 0 0' }}>{stat.sub}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Profile tabs */}
      <div style={{ display: 'flex', gap: 0, borderBottom: `1px solid ${border}`, marginBottom: '1rem' }}>
        {TABS.map(t => (
          <button key={t.id} type="button" onClick={() => setProfileTab(t.id)} style={{
            fontFamily: 'var(--font-inter), Inter, sans-serif', fontSize: 13, fontWeight: 500,
            padding: '8px 14px', background: 'none', border: 'none', cursor: 'pointer',
            color: profileTab === t.id ? '#C4973F' : textSec,
            borderBottom: profileTab === t.id ? '2px solid #C4973F' : '2px solid transparent',
            transition: 'all 150ms', whiteSpace: 'nowrap' as const,
          }}>
            {t.label}
          </button>
        ))}
      </div>

      {/* Tab content */}
      <div style={{ paddingBottom: '2rem' }}>
        {profileTab === 'overview' && <OverviewTab client={client} dm={dm} />}
        {profileTab === 'journey' && <JourneyTab client={client} dm={dm} />}
        {profileTab === 'conversations' && <ConversationsTab client={client} dm={dm} />}
        {profileTab === 'notes' && <NotesTab client={client} dm={dm} />}
        {profileTab === 'settings' && <SettingsTab client={client} dm={dm} />}
      </div>

      {/* Toast */}
      {toast && (
        <div style={{
          position: 'fixed', bottom: 100, left: '50%', transform: 'translateX(-50%)',
          background: '#1A1814', border: '1px solid rgba(196,151,63,0.3)',
          borderRadius: '0.75rem', padding: '12px 20px',
          fontFamily: 'var(--font-inter), Inter, sans-serif', fontWeight: 500, fontSize: 13, color: '#FFFDF8',
          zIndex: 200, whiteSpace: 'nowrap' as const,
        }}>
          {toast} ✦
        </div>
      )}
    </div>
  )
}
